---
title: "Analyse donnees Laboratoire"
author: "Serigne Fallou Mbacke NGOM"
date: "`r Sys.Date()`"
output: html_document
---


## ========= RECODAGE DES VARIABLES ============= #
```{r echo=FALSE, warning=FALSE}
library(readxl)
Rst_labo = data.frame(read_xlsx("C:/STAGE IPD EPIDEMIOLOGIE/TBL_ARBO.xlsx"))
for (i in names(Rst_labo)){
  Rst_labo[, i] = factor(Rst_labo[, i])
}


levels(Rst_labo$SEXE) = c( "Homme","Femme")


for (i in c("ID.EPI", "PRENOM_NOM", 'NUMERO.REGISTRE')){
  Rst_labo[, i] = as.character(Rst_labo[,i])
}


for (i in c("DTE_REC", "DTE_RESUL" )){
  Rst_labo[, i]= as.Date(Rst_labo[, i], '%Y-%m-%d')
}

```


```{r echo=FALSE, warning=FALSE}
for (i in c('IgM.EBOLA.ZAIRE_S', 'IgM.EBOLA.SOUDAN_S', 'IgM.MARBURG_S', 'IgM.LASSA_S')){
  levels(Rst_labo[, i])= c(paste(i, "Non", sep = "_"), paste(i, "nsp", sep = "_"))
}


for (i in c('DEN', 'WN', 'RVF', 'CHIK', 'CCHF')){
  levels(Rst_labo[, i])= c(paste(i, "Non", sep = "_"))
} 


for (i in c('IgM.YF', 'ARN.CHIK', 'ARN.DEN',  'ARN.RVF', 'IGM.RVF')){
  levels(Rst_labo[, i])= c(paste(i, "Oui", sep = "_"), paste(i, "Non", sep = "_"), paste(i, "nsp", sep = "_"), paste(i, "a_ver", sep = "_"))
}


for (i in c('ARN.YF', 'ARN.WN',   'ARN.ZIKA', 'ARN.CCHF', 'ARN.EBOLA.ZAIRE', 'ARN.EBOLA.SOUDAN', 'ARN.MARBURG', 'ARN.LASSA')){
  levels(Rst_labo[, i])= c(paste(i, "Non", sep = "_"), paste(i, "nsp", sep = "_"), paste(i, "a_ver", sep = "_"))
}  


for (i in c('IGM.DEM',  'IGM.WN', 'IGM.CHIK', 'IGM.CHF',  'IGM.CCHF', 'IGM.ZIKA')){
  levels(Rst_labo[, i])= c(paste(i, "Oui", sep = "_"), paste(i, "Non", sep = "_"), paste(i, "nsp", sep = "_"))
}

summary(Rst_labo)
```

## =========== VISUALISATION DES DONNEES ========== ##
```{r echo=FALSE, warning=FALSE}

for (i in c('IgM.YF', 'ARN.CHIK', 'ARN.DEN',  'ARN.RVF', 'IGM.RVF', 'IGM.DEM',  'IGM.WN', 'IGM.CHIK', 'IGM.CHF',  'IGM.CCHF', 'IGM.ZIKA','ARN.YF', 'ARN.WN',   'ARN.ZIKA', 'ARN.CCHF', 'ARN.EBOLA.ZAIRE', 'ARN.EBOLA.SOUDAN', 'ARN.MARBURG', 'ARN.LASSA', 'DEN', 'WN', 'RVF', 'CHIK', 'CCHF', 'IgM.EBOLA.ZAIRE_S', 'IgM.EBOLA.SOUDAN_S', 'IgM.MARBURG_S', 'IgM.LASSA_S', 'CENTRE', "REGION", "TYPE.DE.SITE", "SEXE")) {
  plot(Rst_labo[,i], main = colnames(Rst_labo)[i],
       ylab = "Count", col="steelblue", las = 2)
  }
```

## ======== ANALYSE DES CORRESPONDANCES MULTIPLES ============
### ACM1:

```{r echo=FALSE, warning=FALSE}
library("FactoMineR")
library("factoextra")
library('corrplot')

Rst_labo1 = Rst_labo[,c('ARN.RVF', 'ARN.WN')]
mca.Rst_labo1 <- MCA(Rst_labo1, graph = FALSE)

fviz_screeplot (mca.Rst_labo1, addlabels = TRUE, ylim = c (0, 45))

fviz_mca_biplot(mca.Rst_labo1,axes = c(1, 2), col.var='cos2', gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE, ggtheme=theme_minimal())

fviz_mca_biplot(mca.Rst_labo1,axes = c(1, 3), col.var='cos2', gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE, ggtheme=theme_minimal())

```

```{r echo=FALSE, warning=FALSE}
library("rpart")
library("rpart.plot")
library(tree)
tree.mode1 <- rpart(ARN.RVF ~ ARN.WN , method="class", data=Rst_labo1)
rpart.plot(tree.mode1)

```
**ANALYSE ET INTERPRETATION DES RESULTATS:** 
Les resultats nous montre que les echantillons sans ARN RVF ne possedent egalement pas de ARN WN. 
Donc des l'instant que ARN_RVF est absente donc ARN_WN est aussi absente dans un echantillon.



```{r}
Rst_labo2 = Rst_labo[,c('ARN.CHIK',  'ARN.RVF')]
mca.Rst_labo2 <- MCA(Rst_labo2, graph = FALSE)

fviz_screeplot (mca.Rst_labo2, addlabels = TRUE, ylim = c (0, 45))

fviz_mca_biplot(mca.Rst_labo2,axes = c(1, 2), col.var='cos2', gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE, ggtheme=theme_minimal())

fviz_mca_biplot(mca.Rst_labo2,axes = c(1, 3), col.var='cos2', gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),repel = TRUE, ggtheme=theme_minimal())

```

```{r echo=FALSE, warning=FALSE}
library("rpart")
library("rpart.plot")
library(tree)
tree.mode2 <- rpart(ARN.RVF ~ ARN.CHIK, method="class", data=Rst_labo2)
rpart.plot(tree.mode2)

```





