
mabase$DAT_CST=as.Date(mabase$DAT_CST,'%Y-%m-%d')
mabase$DAT_NAIS=as.Date(mabase$DAT_NAIS,'%Y-%m-%d')
mabase$DAT_DEB=as.Date(mabase$DAT_DEB,'%Y-%m-%d')
mabase$DAT_VAC_FJ=as.Date(mabase$DAT_VAC_FJ,'%Y-%m-%d')
mabase$DAT_VAC_GRIPPE=as.Date(mabase$DAT_VAC_GRIPPE,'%Y-%m-%d')
mabase$DAT_DC=as.Date(mabase$DAT_DC,'%Y-%m-%d')
mabase$DAT_RECEPT=as.Date(mabase$DAT_RECEPT,'%Y-%m-%d')

class(mabase$DAT_DEB)
class(mabase$DAT_CST)
labels(mabase)

mabase$SEXE = factor(mabase$SEXE)
mabase$TOUX = factor(mabase$TOUX)
mabase$FVR = factor(mabase$FVR)
mabase$GRIPPE = factor(mabase$GRIPPE)
mabase$CEPHALEES = factor(mabase$CEPHALEES)
mabase$ARTHRALGIES = factor(mabase$ARTHRALGIES)
mabase$ARBOVIROSE = factor(mabase$ARBOVIROSE)
mabase$D_ORBIT = factor(mabase$D_ORBIT)
mabase$HEMORR = factor(mabase$HEMORR)
mabase$PALUDISME = factor(mabase$PALUDISME)
mabase$MGORGE = factor(mabase$MGORGE)
mabase$RHIN = factor(mabase$RHIN)
mabase$ASTHENIE = factor(mabase$ASTHENIE)
mabase$FRISSONS = factor(mabase$FRISSONS)
mabase$DYSPNE = factor(mabase$DYSPNE)
mabase$PLVTGRIP = factor(mabase$PLVTGRIP)
mabase$PLVTNATUR = factor(mabase$PLVTNATUR)
mabase$MYALG = factor(mabase$MYALG)
mabase$ERUPCUTANE = factor(mabase$ERUPCUTANE)
mabase$X1PLVTARBO = factor(mabase$X1PLVTARBO)
mabase$TDR_YN = factor(mabase$TDR_YN)
mabase$TDR = factor(mabase$TDR)
mabase$GE = factor(mabase$GE)
mabase$FROTTIS = factor(mabase$FROTTIS)
mabase$PALUCONF = factor(mabase$PALUCONF)
mabase$NAUSEES = factor(mabase$NAUSEES)
mabase$DIARRHEES = factor(mabase$DIARRHEES)
mabase$VOMISSEMENTS = factor(mabase$VOMISSEMENTS)
mabase$ICTERE = factor(mabase$ICTERE)
mabase$NEUROL = factor(mabase$NEUROL)
mabase$R_NUQUE = factor(mabase$R_NUQUE)
mabase$GANGLION = factor(mabase$GANGLION)
mabase$SPLENOMEGALIE = factor(mabase$SPLENOMEGALIE)
mabase$ANEMIE = factor(mabase$ANEMIE)
mabase$AUTRES = factor(mabase$AUTRES)
mabase$AUTR_SIGN = factor(mabase$AUT_SIGN)
mabase$AUT_SIGN2 = factor(mabase$AUT_SIGN2)
mabase$AUT_SIGN3 = factor(mabase$AUT_SIGN3)
mabase$VOYAGE =factor(mabase$VOYAGE)
mabase$ATBT = factor(mabase$ATBT)
mabase$AT_PALU = factor(mabase$AT_PALU)
mabase$ATHIS = factor(mabase$ATHIS)
mabase$AT_PYR = factor(mabase$AT_PYR)
mabase$BRONC = factor(mabase$BRONC)
mabase$AUT_TT = factor(mabase$AUT_TT)
mabase$RET_DOM = factor(mabase$RET_DOM)
mabase$HOSP = factor(mabase$HOSP)
mabase$DCD = factor(mabase$DCD)
mabase$AUT_EVOL = factor(mabase$AUT_EVOL)
mabase$EVOL = factor(mabase$EVOL) 
mabase$VAC_FJ = factor(mabase$VAC_FJ)
mabase$VAC_GRIPPE = factor(mabase$VAC_GRIPPE)
mabase$ENTOURAGE = factor(mabase$ENTOURAGE)
mabase$NBJ_HOSP = factor(mabase$NBJ_HOSP)

summary(mabase)